version: '3'

services:
  helpbot-be:
    image: aakashdocker0991/helpbot-be:latest
    ports:
      - "8000:8000"
    environment:
      - OPENAI_API_KEY=<<YOUR OPEN AI KEY>>

  helpbot-fe:
    image: aakashdocker0991/helpbot-fe:latest
    ports:
      - "7000:7000"
    depends_on:
      - helpbot-be
